### PR TITLE
Update td-agent.yml

### PR DESCRIPTION
**Pull request by zopar**
Add development package installation to prevent error on fluent-plugin-prometheus installation

### CODE REVIEW

**Comment by zopar** [comment]
To avoid the error during server provision:
TASK [command] *****************************************************************
failed: [server] (item=fluent-plugin-prometheus) => {"changed": true, "cmd": "/usr/sbin/td-agent-gem install fluent-plugin-prometheus" ...

**Comment by zopar** [comment]
To prevent this error during server provision:
TASK [command] *****************************************************************
failed: [server] (item=fluent-plugin-prometheus) => {"changed": true, "cmd": "/usr/sbin/td-agent-gem install fluent-plugin-prometheus"

**Comment by zopar** [comment]
Sorry I closed the request by mistake, I opened it again

**Comment by tmtk75** [comment]
Thanks! @zopar

**Pull request merged**
